### ISSUE TITLE
Run problems because of undefined maintenanceMode

### ISSUE THREAD

**Issue by bebablub** [Ogadai/zwift-second-screen#2]
I have the following versions installed:
npm -v
3.5.2
node -v
v8.10.0

After running:
npm install
npm run build
without any errors

i get:

```
npm run start

> zwift-second-screen@0.1.26 start /home/xxx/zwift-second-screen
> node index.js

/home/xxx/zwift-second-screen/server/server.js:40
    if (this.siteSettings.maintenanceMode) {
                          ^

TypeError: Cannot read property 'maintenanceMode' of undefined
    at new Server (/home/xxx/zwift-second-screen/server/server.js:40:27)
    at Object.<anonymous> (/home/xxx/zwift-second-screen/index.js:5:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 4.15.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! zwift-second-screen@0.1.26 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zwift-second-screen@0.1.26 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zwift-second-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zwift-second-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zwift-second-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/zwift-second-screen/npm-debug.log
```
Any ideas on whats going wrong? Wrong node version? What are the requirements?

Thank you!

Kind regards

**Comment by bebablub** [comment]
Some problems with latest node:
node -v
v10.13.0

**Comment by Ogadai** [comment]
Hi @bebablub 

My apologies, but since the GDPR changes back in spring, and Zwift's new Developer API, it's now only possible to run zwift-second-screen if you have a developer account. Unfortunately, Zwift aren't currently able to give out developer accounts, except in special cases.
More details at the [zwift-mobile-api](https://github.com/Ogadai/zwift-mobile-api) project, which this project uses.

That's not causing the error though (I usually run it via my other project zwift-hosted, which passes the settings in). I just wanted to make sure you don't waste any more time trying to get this working without an account.

Regards,
Andy
